// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "com.gigawhitlocks.hackernews",
  "name": "Hacker News",
  "description": "Extended description for Hacker News links",
  "version": "0.2.0",
  "min_server_version": "5.20.0",
  "server": {
    "executables": {
      "darwin-amd64": "",
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "windows-amd64": ""
    },
    "executable": ""
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": []
  }
}
`

func init() {
	manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
